import {beforeEach,test,mock} from 'node:test'
import assert from 'node:assert/strict'
import {build} from 'esbuild'
import {fileURLToPath} from 'node:url'
const built=await build({entryPoints:[fileURLToPath(new URL('../src/services/onCallOpenNotifications.ts',import.meta.url))],bundle:true,write:false,platform:'node',format:'esm'})
const notifications=await import(`data:text/javascript;base64,${Buffer.from(built.outputFiles[0].text).toString('base64')}`)
const row=()=>({id:1,handoffId:4,eventVersion:0,recipientId:3,deliveryKey:'2757c5b4-aa17-4f08-8368-4e8294e13628',status:'PENDING',version:0,attempts:0,nextAttemptAt:'2026-10-11T10:00:00.123456',leaseUntil:null,lastHttpStatus:null,lastErrorCode:null,deliveredAt:null})
const facts=()=>({adapterImplemented:true,enabled:true,databaseNow:'2026-10-11T10:00:00.123456',deliveries:[row()]})
beforeEach(()=>{mock.restoreAll();globalThis.localStorage={getItem:key=>key==='opspilot_user'?JSON.stringify({id:1}):'test-only-token'};globalThis.window=new EventTarget()})
const parse=f=>notifications.parseOpenNotificationFacts(f,4)
test('five technical states never imply human acceptance; disabled configuration preserves historical success',()=>{
  for(const state of ['PENDING','CLAIMED','DELIVERED','FAILED','SKIPPED']){const f=facts(),r=f.deliveries[0];r.status=state;if(state!=='PENDING')r.attempts=1;if(state==='CLAIMED')r.leaseUntil='2026-10-11T10:00:30';if(state==='DELIVERED'){r.lastHttpStatus=204;r.deliveredAt='2026-10-11T10:00:01';f.enabled=false}assert.equal(parse(f).deliveries[0].status,state);assert.ok(notifications.openDeliveryMeaning(r))}
  assert.match(notifications.openDeliveryMeaning({...row(),status:'DELIVERED'}),/不证明本人已读或自愿接班/)
})
test('missing implementation enabled time array or contradictory delivery metadata fails closed',()=>{
  for(const change of [f=>delete f.enabled,f=>f.adapterImplemented='true',f=>f.databaseNow='2026-02-30T10:00:00',f=>f.deliveries=null,f=>f.deliveries[0].leaseUntil='2026-10-11T10:00:30',f=>f.deliveries[0].deliveredAt='2026-10-11T10:00:00',f=>f.deliveries[0].eventVersion=1]){const f=facts();change(f);assert.throws(()=>parse(f))}
})
test('cross-request duplicate recipient key or invalid versions cannot render as current facts',()=>{
  for(const change of [f=>f.deliveries[0].handoffId=5,f=>f.deliveries.push({...row(),id:2}),f=>f.deliveries[0].version=-1,f=>f.deliveries[0].attempts=11,f=>f.deliveries[0].deliveryKey='bad',f=>f.deliveries[0].status='unknown',f=>f.deliveries[0].lastErrorCode='secret provider text']){const f=facts();change(f);assert.throws(()=>parse(f))}
})
test('delivered requires actual 2xx attempt timestamp with no lease or error',()=>{
  const delivered=()=>{const f=facts();Object.assign(f.deliveries[0],{status:'DELIVERED',attempts:1,lastHttpStatus:200,deliveredAt:'2026-10-11T10:00:01'});return f}
  assert.equal(parse(delivered()).deliveries[0].lastHttpStatus,200)
  for(const change of [r=>r.lastHttpStatus=503,r=>r.lastHttpStatus=null,r=>r.attempts=0,r=>r.deliveredAt=null,r=>r.lastErrorCode='TRANSPORT_ERROR']){const f=delivered();change(f.deliveries[0]);assert.throws(()=>parse(f))}
})
test('claimed is only a lease observation, never client expiry or delivery',()=>{const f=facts();Object.assign(f.deliveries[0],{status:'CLAIMED',attempts:1,leaseUntil:'2020-01-01T00:00:00'});assert.equal(parse(f).deliveries[0].status,'CLAIMED');assert.match(notifications.openDeliveryMeaning(f.deliveries[0]),/不按浏览器时钟/);f.deliveries[0].leaseUntil=null;assert.throws(()=>parse(f))})
test('technical parser drops payload URL channel token lease owner and unknown receipt fields',()=>{const f=facts();Object.assign(f.deliveries[0],{payload:'must not retain',url:'https://private',token:'test-token',leaseToken:'opaque-owner',humanAccepted:true});Object.assign(f,{provider:'private'});const p=parse(f);assert.ok(!/private|must not retain|opaque-owner|humanAccepted/.test(JSON.stringify(p)));assert.equal(p.deliveries[0].deliveryKey,row().deliveryKey)})
test('bounded array allows empty and 500 distinct original recipients, rejects 501',()=>{const f=facts();f.deliveries=[];assert.deepEqual(parse(f).deliveries,[]);f.deliveries=Array.from({length:500},(_,i)=>({...row(),id:i+1,recipientId:i+1,deliveryKey:(i+1).toString(16).padStart(8,'0')+'-0000-0000-0000-000000000000'}));assert.equal(parse(f).deliveries.length,500);f.deliveries.push({...row(),id:501,recipientId:501});assert.throws(()=>parse(f))})
test('database timestamp formatting does not use browser timezone or lose microseconds',()=>{assert.equal(notifications.openNotificationClock('2026-10-11T10:00:00.123456'),'2026-10-11 10:00:00.123456');assert.match(notifications.openNotificationClock('2026-10-11T10:00:00Z'),/未取得/);assert.match(notifications.openDeliveryLabel(row()),/尚未尝试/);assert.match(notifications.openDeliveryLabel({...row(),attempts:1}),/自动重试/)})
test('authenticated read is exact GET with captured token and no commands or body',async()=>{const calls=[];mock.method(globalThis,'fetch',async(url,init)=>{calls.push({url,init});return new Response(JSON.stringify({success:true,data:facts()}),{status:200})});const controller=new AbortController();await notifications.readOpenNotifications(4,{actorId:1,token:'test-only-token'},controller.signal);assert.equal(calls.length,1);assert.equal(calls[0].url,'/api/v1/on-call/open-handoffs/4/notifications');assert.equal(calls[0].init.headers.get('Authorization'),'Bearer test-only-token');assert.equal(calls[0].init.body,undefined);assert.equal(calls[0].init.signal,controller.signal);assert.equal(calls[0].init.method,undefined)})
test('bad target session or native token switch causes zero network reads',async()=>{let calls=0;mock.method(globalThis,'fetch',async()=>{calls++;throw Error('unexpected')});for(const [id,session] of [[0,{actorId:1,token:'test-only-token'}],[4,{actorId:3,token:'test-only-token'}],[4,{actorId:1,token:'rotated'}],[4,{actorId:1,token:null}]])await assert.rejects(()=>notifications.readOpenNotifications(id,session));assert.equal(calls,0)})
test('503 malformed facts and transport errors never become empty success or trigger retry commands',async()=>{let calls=0;mock.method(globalThis,'fetch',async()=>{calls++;return new Response(JSON.stringify({success:false,error:{message:'controlled failure',code:'FAIL'}}),{status:503})});await assert.rejects(()=>notifications.readOpenNotifications(4,{actorId:1,token:'test-only-token'}));assert.equal(calls,1);mock.restoreAll();mock.method(globalThis,'fetch',async()=>new Response(JSON.stringify({success:true,data:{}}),{status:200}));await assert.rejects(()=>notifications.readOpenNotifications(4,{actorId:1,token:'test-only-token'}),/事实异常/);mock.restoreAll();mock.method(globalThis,'fetch',async()=>{throw Error('network')});await assert.rejects(()=>notifications.readOpenNotifications(4,{actorId:1,token:'test-only-token'}),/network/)})
test('service 401 emits existing session expiration and never stores channel data',async()=>{let expired=0;window.addEventListener('opspilot-auth-expired',()=>expired++);mock.method(globalThis,'fetch',async()=>new Response('',{status:401}));await assert.rejects(()=>notifications.readOpenNotifications(4,{actorId:1,token:'test-only-token'}),/登录已过期/);assert.equal(expired,1)})
