const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {verify:verifyRaw}=require('../verify-oncall-plan-membership-ui-evidence.cjs'),{caseNames,originalCaseNames}=require('../verify-oncall-plan-membership-ui-ci.cjs');
const root=path.resolve(__dirname,'../..');
// Explicit gate fixture, not a claim of browser execution; actual raw evidence is inspected separately.
function fixture(){const names=['after-first-desktop.png','after-desktop.png','after-first-mobile.png','after-mobile.png','original-vs-current-desktop.png','locked-original-mobile.png','frozen-original-mobile.png','first-null-receipt-desktop.png','after-clear-uncertain-desktop.png','native-cross-tab-frozen-mobile.png'];const cases=caseNames.map(name=>({name}));for(const i of [2,3,4,9,10])cases[i].posts=0;
Object.assign(cases[5],{posts:1,actualForwardedCommit200:true,browserRequestAborted:true,originalCommand:{expectedVersion:0},currentVersion:2});Object.assign(cases[6],{ownPlanManagementRemoved:true,originalReadOnlyAck200:true});Object.assign(cases[7],{actual409:409,versionNotRebased:true});cases[8].actual403=403;for(const [i,f]of [[11,'originalPreserved'],[12,'newActorDraftPreserved'],[13,'newTokenIdentityProtected']])Object.assign(cases[i],{committedLate200:true,[f]:true});
Object.assign(cases[14],{expectedVersion:null,explicitExpectedVersionPresent:true,actualHttp200:true,version:0,origin:'EXPLICIT',responseOnly:true});for(const i of [15,16,17])Object.assign(cases[i],{actualCommit200:true,posts:2,manualSameOriginalBody:true,clearPhysicallyAbsent:i===17});for(const i of [18,19])Object.assign(cases[i],{posts:0,originalRetained:true});Object.assign(cases[20],{actualCommit200:true,contradictoryActorRejected:true,manualOriginalAck200:true});Object.assign(cases[21],{posts:0,contradictoryFactsCleared:true});Object.assign(cases[22],{actual409:409,lockSaveFailedWarning:true,reloadPosts:0,originalCommandRetained:true});for(const i of [23,24])Object.assign(cases[i],{nativeStorageEvents:true,committedLate200:true,originalRetained:true,syntheticStorageEventDispatched:false});
const sql=mode=>({allOwnedJarsStopped:true,receipt:{actualProduct:'H2',migration39:true,newUserId:90,businessBefore:'b'.repeat(64),businessAfter:'b'.repeat(64),mode,changedUsers:mode==='SEED'?1:0,memberRows:mode==='SEED'?0:1,memberOperations:mode==='SEED'?0:1,explicitResponseOnlyVersion0:mode==='SEED'?0:1,explicitNullActor1Receipt:mode==='SEED'?0:1}});
return{status:'PASS',baseline:false,previous:false,cases,screenshots:names,visualBounds:names.map(name=>({name,width:name.includes('mobile')?390:1440,documentWidth:name.includes('mobile')?390:1440})),ownedProcessStopped:true,portsFree:true,completePoolShutdown:true,tokensPersistedToEvidence:false,userDatabaseModified:false,unexpectedJarErrors:0,pageErrors:[],console:[],expectedRejections:[],jarSha256:'a'.repeat(64),startedPid:13,startedPids:[12,13],stoppedPids:[12,13],sqlFixtures:[sql('SEED'),sql('SNAPSHOT')],viewports:['1440x1000','390x844'],browserPath:'Browser plugin not available; existing Playwright'};}
const log='HikariPool-1 - Start completed.\nHikariPool-1 - Shutdown completed.';
const verify=(result,raw=log)=>verifyRaw(result,raw,log);
test('explicit synthetic gate fixture passes without claiming actual execution',()=>assert.equal(verify(fixture(),log).browserCases,25));
test('baseline missing case error or screenshot clipping cannot substitute own UI',()=>{for(const change of [r=>r.baseline=true,r=>r.cases.pop(),r=>r.status='FAIL',r=>r.pageErrors.push('runtime'),r=>r.visualBounds[3].documentWidth=500,r=>r.screenshots.pop()]){const r=fixture();change(r);assert.throws(()=>verify(r,log));}});
test('zero POST reliable-save and original/higher current receipt are required',()=>{for(const change of [r=>r.cases[2].posts=1,r=>r.cases[5].actualForwardedCommit200=false,r=>r.cases[5].currentVersion=1,r=>r.cases[6].originalReadOnlyAck200=false]){const r=fixture();change(r);assert.throws(()=>verify(r,log));}});
test('actual 403409 and all three late identity protections required',()=>{for(const change of [r=>r.cases[7].actual409=200,r=>r.cases[8].actual403=200,r=>r.cases[11].originalPreserved=false,r=>r.cases[12].newActorDraftPreserved=false,r=>r.cases[13].newTokenIdentityProtected=false]){const r=fixture();change(r);assert.throws(()=>verify(r,log));}});
test('unexpected console paths statuses and incomplete owned pool shutdown fail',()=>{for(const change of [r=>r.portsFree=false,r=>r.completePoolShutdown=false,r=>r.console.push({text:'Failed to load resource:',url:'/other'}),r=>r.expectedRejections.push({path:'/api/v1/on-call/schedules/1/members',status:401})]){const r=fixture();change(r);assert.throws(()=>verify(r,log));}assert.throws(()=>verify(fixture(),'HikariPool-1 - Start completed.'));});
test('new UI preserves original frozen storage fences and independent permissions',()=>{const panel=fs.readFileSync(path.join(root,'web/src/components/OnCallPlanMemberPanel.vue'),'utf8');for(const text of ['saveMemberIntent(sessionStorage,draft)','submitMemberIntent(sessionStorage,draft,identity.token)','if(!current(identity))return','draft.blocked=true','手动求成员原回执','v-model="intent.command.canRespond"','v-model="intent.command.canManage"'])assert.ok(panel.includes(text));assert.ok(panel.indexOf('saveMemberIntent(sessionStorage,draft)')<panel.indexOf('submitMemberIntent(sessionStorage,draft,identity.token)'));assert.ok(panel.includes('identity.token===localStorage.getItem'));assert.ok(panel.includes('identity.actor===sessionActor()'));});
test('explicit null first grant cannot substitute implicit membership or synthetic response label',()=>{for(const change of [r=>r.previous=true,r=>r.cases[14].expectedVersion=0,r=>r.cases[14].explicitExpectedVersionPresent=false,r=>r.sqlFixtures[0].receipt.memberRows=1,r=>r.sqlFixtures[1].receipt.explicitNullActor1Receipt=0]){const r=fixture();change(r);assert.throws(()=>verify(r));}});
test('clear-after-remove recovery native events and complete two JVM SQL lifecycle required',()=>{for(const change of [r=>r.cases[17].clearPhysicallyAbsent=false,r=>r.cases[17].manualSameOriginalBody=false,r=>r.cases[23].syntheticStorageEventDispatched=true,r=>r.cases[24].nativeStorageEvents=false,r=>r.stoppedPids.pop(),r=>r.sqlFixtures[0].allOwnedJarsStopped=false]){const r=fixture();change(r);assert.throws(()=>verify(r));}assert.throws(()=>verifyRaw(fixture(),log,undefined));});
test('all 14 original names unchanged and only current runner can run full CI',()=>{const prior=require('node:child_process').execFileSync('git',['show','ea4ac9fe3d22bfcd7bf2b2c59362b3ccc6c536b0:scripts/verify-oncall-plan-membership-ui-ci.cjs'],{cwd:root,encoding:'utf8'});const old=JSON.parse('['+prior.match(/const caseNames=\[([^\r\n]+)\];/)[1].replaceAll("'",'"')+']');assert.deepEqual(originalCaseNames,old);assert.deepEqual(caseNames.slice(0,14),old);const runner=fs.readFileSync(path.join(root,'scripts/verify-oncall-plan-membership-ui-ci.cjs'),'utf8');assert.ok(runner.includes('assert.ok(!(baseline||previous)||!process.env.CI'));assert.ok(runner.includes('allOwnedJarsStopped:true'));const source=fs.readFileSync(path.join(root,'scripts/fixtures/PlanMemberUiAccountFixture.java'),'utf8');for(const text of ['IFEXISTS=TRUE','toRealPath()','oncall-plan-membership-ui-it','INSERT INTO sys_user','version=0','expected_version IS NULL'])assert.ok(source.includes(text));assert.doesNotMatch(source,/DELETE FROM|DROP TABLE|ALTER TABLE/);});
