const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {verify,suite,cases}=require('../verify-oncall-open-handoff-recipients.cjs');
function fixture(){const ids=cases.map(name=>'OPEN_RECIPIENT_DATABASE '+JSON.stringify({case:name,product:'MySQL',version:'8.4.11',schema:'opspilot_open_recipient_test',migration40:true,migration41:true}));
  return{log:'INFO HikariPool-1 - Start completed.\n'+ids.join('\n')+'\nINFO HikariPool-1 - Shutdown completed.\n[INFO] BUILD SUCCESS\n',
    xml:'<testsuite name="'+suite+'" tests="14" failures="0" errors="0" skipped="0">'+cases.map((name,i)=>'<testcase classname="'+suite+'" name="'+name+'"><system-out><![CDATA['+ids[i]+']]></system-out></testcase>').join('')+'</testsuite>'};}
const run=f=>verify(f.log,f.xml);
test('synthetic recipient gate shape is explicitly not actual MySQL delivery or reminder proof',()=>{const r=run(fixture());assert.equal(r.executed,14);assert.equal(r.actualDeliveryVerified,false);assert.equal(r.remindersVerified,false);});
test('all shared Java cases match the explicit positive and negative gate IDs',()=>{const s=fs.readFileSync(path.resolve(__dirname,'../../src/test/java/org/trigger/opspilot/oncall/OpenHandoffRecipientScenarios.java'),'utf8');assert.deepEqual([...s.matchAll(/@Test\s+void\s+(\w+)\(/g)].map(m=>m[1]).sort(),[...cases].sort());});
test('zero skipped failed duplicated renamed and omitted cases cannot pass',()=>{for(const mutate of [f=>f.xml=f.xml.replace('tests="14"','tests="0"'),f=>f.xml=f.xml.replace('skipped="0"','skipped="1"'),f=>f.xml=f.xml.replace('<system-out>','<failure/><system-out>'),f=>f.xml=f.xml.replace(cases[1],cases[0]),f=>f.xml=f.xml.replace(cases[1],'renamed')]){const f=fixture();mutate(f);assert.throws(()=>run(f));}});
test('each XML and full log must agree on real owned MySQL 8.4 and V40',()=>{for(const mutate of [f=>f.xml=f.xml.replace('"product":"MySQL"','"product":"H2"'),f=>f.xml=f.xml.replace('8.4.11','8.0.1'),f=>f.xml=f.xml.replace('opspilot_open_recipient_test','production'),f=>f.xml=f.xml.replace('"migration40":true','"migration40":false'),f=>f.log=f.log.replace('8.4.11','8.4.12')]){const f=fixture();mutate(f);assert.throws(()=>run(f));}});
test('build failure unexpected errors missing pools and partial shutdown cannot pass',()=>{for(const mutate of [f=>f.log=f.log.replace('BUILD SUCCESS','BUILD FAILURE'),f=>f.log+='ERROR late shutdown failure\n',f=>f.log=f.log.replace('Start completed.','Starting...'),f=>f.log=f.log.replace('Shutdown completed.','Shutdown initiated.'),f=>f.log=f.log.replace('HikariPool-1 - Shutdown','HikariPool-2 - Shutdown')]){const f=fixture();mutate(f);assert.throws(()=>run(f));}});
test('production claim and candidate SQL share exact response qualification and snapshot contains no command secrets',()=>{const root=path.resolve(__dirname,'../..'),m=fs.readFileSync(root+'/src/main/java/org/trigger/opspilot/oncall/OnCallPlanMembershipService.java','utf8'),r=fs.readFileSync(root+'/src/main/java/org/trigger/opspilot/oncall/OnCallOpenHandoffRecipients.java','utf8');assert.match(m,/formatted\(RESPONSE_ELIGIBILITY\)/);assert.match(r,/formatted\(OnCallPlanMembershipService\.RESPONSE_ELIGIBILITY,OnCallPlanMembershipService\.RESPONSE_ELIGIBILITY\)/);assert.doesNotMatch(r,/requestKey\(|reason\(|password|Authorization/);assert.match(r,/filter\(capturedIds::contains\)/);assert.match(r,/Propagation\.MANDATORY/);});
test('WIP preserves four existing jobs while adding separate actual MySQL recipient job',()=>{const yaml=fs.readFileSync(path.resolve(__dirname,'../../.github/workflows/plan-membership-wip.yml'),'utf8');assert.match(yaml,/-Dtest=MySqlOnCallOpenHandoffRecipientIntegrationTest test/);assert.match(yaml,/node scripts\/verify-oncall-open-handoff-recipients.cjs/);assert.doesNotMatch(yaml,/continue-on-error/);});
test('member UI original-case comparison has full immutable Git history in its own job',()=>{const yaml=fs.readFileSync(path.resolve(__dirname,'../../.github/workflows/plan-membership-wip.yml'),'utf8'),block=yaml.match(/  membership-ui:([\s\S]*?)(?=\n  [\w-]+:)/)[1];assert.match(block,/actions\/checkout@v5\s+with:\s+fetch-depth: 0/);assert.match(block,/node --test scripts\/tests\/oncall-plan-membership-ui.test.cjs/);});
