const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {verify}=require('../verify-oncall-open-notification-ui-evidence.cjs');
// Replay actual archived local evidence; these gate tests are not another browser execution.
function fixture(){const dir=path.resolve(__dirname,'../../docs/assets/v1.7-cp119/final-notification-ui');return{r:JSON.parse(fs.readFileSync(dir+'/result.json','utf8')),read:name=>fs.readFileSync(dir+'/'+name)};}
const run=f=>verify(f.r,f.read),rejects=changes=>{for(const change of changes){const f=fixture();change(f);assert.throws(()=>run(f));}};
test('actual notification UI raw evidence independently proves eleven scoped cases',()=>{const p=run(fixture());assert.equal(p.cases,11);assert.equal(p.browserBusinessPosts,0);assert.equal(p.actualConfiguredReceiverHttp,4);assert.equal(p.noAutomaticHumanClaim,true);});
test('archived baseline missing case and page errors cannot substitute current UI',()=>rejects([f=>f.r.before=true,f=>f.r.cases.pop(),f=>f.r.cases[0].name='invented',f=>f.r.pageErrors.push('runtime'),f=>f.r.status='FAIL']));
test('UI posts or automatic human acceptance reject technical delivery evidence',()=>rejects([f=>f.r.browserPosts.push('/api/v1/on-call/open-handoffs/1/claim'),f=>f.r.cases[3].posts=1,f=>f.r.sqlFixtures[0].requests[0].claimedBy=1,f=>f.r.cases[5].requestStillOpen=false]));
test('observed HTTP credentials immutable key payload and recipient required',()=>rejects([f=>f.r.received[0].authenticated=false,f=>f.r.received[3].key='replacement',f=>f.r.received[3].payloadSha256='0'.repeat(64),f=>f.r.received[2].recipientId=3,f=>f.r.received[1].status=200]));
test('real lease and 503 retry cannot be fabricated from pending success',()=>rejects([f=>f.r.cases[1].actualClaimed.status='PENDING',f=>f.r.cases[1].actualClaimed.leaseUntil=null,f=>f.r.cases[2].actualPendingAfter503.lastHttpStatus=200,f=>f.r.cases[2].actualPendingAfter503.deliveredAt='2026-10-10T00:00:00']));
test('fresh failure and late request native actor fences must all be observed',()=>rejects([f=>f.r.cases[6].oldFactsCleared=false,f=>f.r.cases[7].controlledContradictoryMetadata=false,f=>f.r.cases[8].selectedRequestPreserved=false,f=>f.r.cases[9].nativeStorageEvent=false,f=>f.r.cases[10].actualAuditor200=false]));
test('missing complete shutdown pool logs screenshot hash or clipping fail closed',()=>rejects([f=>f.r.stoppedPids.pop(),f=>f.r.receiverStopped=false,f=>f.r.portsFree=false,f=>f.r.screenshots[0].sha256='0'.repeat(64),f=>f.r.screenshots[1].bounds.scroll=700,f=>{const read=f.read;f.read=name=>name==='jar-3.log'?Buffer.from(read(name).toString().replace('Shutdown completed.','Shutdown initiated.')):read(name);} ]));
test('read-only child has no mutation endpoint and route cancellation errors reach runner cleanup',()=>{const root=path.resolve(__dirname,'../..'),service=fs.readFileSync(root+'/web/src/services/onCallOpenNotifications.ts','utf8'),panel=fs.readFileSync(root+'/web/src/components/OnCallOpenNotificationPanel.vue','utf8'),runner=fs.readFileSync(root+'/scripts/verify-oncall-open-notification-ui-ci.cjs','utf8');assert.doesNotMatch(service,/method:\s*['"]POST|\/claim|\/retry/);for(const text of ['controller?.abort()','identity.handoffId===props.handoffId','identity.token===sessionToken()','facts.value=null','identity.actorId===sessionActor()'])assert.ok(panel.includes(text));assert.ok(runner.includes('await done;await page.unroute'));assert.ok(runner.includes('if(failure)throw failure'));});
