const {test}=require('node:test'),assert=require('node:assert/strict');
const {verify,suite,requiredCase,states}=require('../verify-oncall-swap-notification-migration-mysql.cjs');
function fixture(){const db=phase=>({case:requiredCase,phase,product:'MySQL',version:'8.4.11',schema:'opspilot_swap_notification_migration_test',rows:10});
  const result={case:requiredCase,rows:10,legacyColumns:21,states,stateCounts:Object.fromEntries(states.map(s=>[s,2])),pastRows:5,futureRows:5,upgradeMigrations:1,repeatMigrations:0,legacyHistoryBeforeSha256:'a'.repeat(64),legacyHistoryAfterSha256:'a'.repeat(64),allDeadlinesEqualCreatedPlus30Days:true,microsecondsPreserved:true,allPayloadsNotErased:true,parentCountsUnchanged:true,pastAndFutureRows:true,retentionIndexColumns:['payload_erased_at','payload_expires_at','id'],parentCounts:{audit_log:2,oncall_shift:2,oncall_shift_swap:1,sys_user:4}};
  const body=[['DATABASE',db('V35_BEFORE')],['DATABASE',db('V36_AFTER')],['RESULT',result],['CONTAINER_STOPPED',{case:requiredCase,stopped:true}]].map(([k,v])=>'CP91_SWAP_NOTIFICATION_MIGRATION_'+k+' '+JSON.stringify(v)).join('\n');
  return {body,xml:`<testsuite name="${suite}" tests="1" failures="0" errors="0" skipped="0"><testcase name="${requiredCase}"><system-out><![CDATA[${body}]]></system-out></testcase></testsuite>`,log:body+'\n[INFO] BUILD SUCCESS\n'};}
const run=f=>verify(f.log,f.xml);
const change=(f,from,to)=>{f.log=f.log.replace(from,to);f.xml=f.xml.replace(from,to);return f;};
test('synthetic populated upgrade fixture proves gate shape only, not a MySQL execution',()=>assert.equal(run(fixture()).upgrade.rows,10));
test('skips failures errors and missing or duplicate actual test cannot pass',()=>{for(const [from,to] of [['skipped="0"','skipped="1"'],['tests="1"','tests="0"'],['errors="0"','errors="1"'],['failures="0"','failures="1"'],['name="'+requiredCase+'"','name="other"'],['</testsuite>','']]){const f=fixture();f.xml=f.xml.replace(from,to);assert.throws(()=>run(f));}});
test('H2 wrong version schema phase or population is rejected in matching log and XML',()=>{for(const [from,to] of [['"product":"MySQL"','"product":"H2"'],['"version":"8.4.11"','"version":"8.0.1"'],['"schema":"opspilot_swap_notification_migration_test"','"schema":"foreign"'],['V35_BEFORE','V36_AFTER'],['"rows":10','"rows":0']])assert.throws(()=>run(change(fixture(),from,to)));});
test('original history hash columns and one-time migration cannot silently change',()=>{for(const [from,to] of [['"legacyColumns":21','"legacyColumns":20'],['"upgradeMigrations":1','"upgradeMigrations":0'],['"repeatMigrations":0','"repeatMigrations":1'],['"legacyHistoryAfterSha256":"'+ 'a'.repeat(64)+'"','"legacyHistoryAfterSha256":"'+ 'b'.repeat(64)+'"']])assert.throws(()=>run(change(fixture(),from,to)));});
test('every state deadline microsecond erasure index and parent invariant is mandatory',()=>{for(const flag of ['allDeadlinesEqualCreatedPlus30Days','microsecondsPreserved','allPayloadsNotErased','parentCountsUnchanged','pastAndFutureRows'])for(const value of ['false','null','"true"'])assert.throws(()=>run(change(fixture(),'"'+flag+'":true','"'+flag+'":'+value)));
  for(const [from,to] of [['"CLAIMED":2','"CLAIMED":1'],['"pastRows":5','"pastRows":0'],['"futureRows":5','"futureRows":0'],['["payload_erased_at","payload_expires_at","id"]','["payload_expires_at","payload_erased_at","id"]'],['"oncall_shift_swap":1','"oncall_shift_swap":0']])assert.throws(()=>run(change(fixture(),from,to)));});
test('result identity global-only missing or duplicate evidence cannot pass',()=>{for(const prefix of ['DATABASE','RESULT','CONTAINER_STOPPED']){const f=fixture();f.xml=f.xml.replace('CP91_SWAP_NOTIFICATION_MIGRATION_'+prefix,'wrong');assert.throws(()=>run(f));}
  const f=fixture();f.log=f.log.replace('"stopped":true','"stopped":false');assert.throws(()=>run(f));});
test('missing early or false container stop and post-summary errors fail closed',()=>{for(const mutate of [f=>change(f,'"stopped":true','"stopped":false'),f=>change(f,'CONTAINER_STOPPED','STOP_NOT_SEEN'),f=>{f.log='CP91_SWAP_NOTIFICATION_MIGRATION_CONTAINER_STOPPED '+JSON.stringify({case:requiredCase,stopped:true})+'\n'+f.log;},f=>{f.log+='[ERROR] shutdown failure';},f=>{f.log=f.log.replace('BUILD SUCCESS','missing');}]){const f=fixture();mutate(f);assert.throws(()=>run(f));}});
test('complete ANSI CRLF evidence remains accepted without relaxing assertions',()=>{const f=fixture();f.log='\u001b[32m'+f.log.replaceAll('\n','\r\n')+'\u001b[0m';assert.equal(run(f).status,'PASS');});
