const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {verify}=require('../verify-oncall-plan-membership-ui-evidence.cjs'),{caseNames}=require('../verify-oncall-plan-membership-ui-ci.cjs');
const root=path.resolve(__dirname,'../..');
// Explicit gate fixture, not a claim of browser execution; actual raw evidence is inspected separately.
function fixture(){const names=['after-first-desktop.png','after-desktop.png','after-first-mobile.png','after-mobile.png','original-vs-current-desktop.png','locked-original-mobile.png','frozen-original-mobile.png'];const cases=caseNames.map(name=>({name}));for(const i of [2,3,4,9,10])cases[i].posts=0;
Object.assign(cases[5],{posts:1,actualForwardedCommit200:true,browserRequestAborted:true,originalCommand:{expectedVersion:0},currentVersion:2});Object.assign(cases[6],{ownPlanManagementRemoved:true,originalReadOnlyAck200:true});Object.assign(cases[7],{actual409:409,versionNotRebased:true});cases[8].actual403=403;for(const [i,f]of [[11,'originalPreserved'],[12,'newActorDraftPreserved'],[13,'newTokenIdentityProtected']])Object.assign(cases[i],{committedLate200:true,[f]:true});
return{status:'PASS',baseline:false,cases,screenshots:names,visualBounds:names.map(name=>({name,width:name.includes('mobile')?390:1440,documentWidth:name.includes('mobile')?390:1440})),ownedProcessStopped:true,portsFree:true,completePoolShutdown:true,tokensPersistedToEvidence:false,userDatabaseModified:false,unexpectedJarErrors:0,pageErrors:[],console:[],expectedRejections:[],jarSha256:'a'.repeat(64),startedPid:12,viewports:['1440x1000','390x844'],browserPath:'Browser plugin not available; existing Playwright'};}
const log='HikariPool-1 - Start completed.\nHikariPool-1 - Shutdown completed.';
test('explicit synthetic gate fixture passes without claiming actual execution',()=>assert.equal(verify(fixture(),log).browserCases,14));
test('baseline missing case error or screenshot clipping cannot substitute own UI',()=>{for(const change of [r=>r.baseline=true,r=>r.cases.pop(),r=>r.status='FAIL',r=>r.pageErrors.push('runtime'),r=>r.visualBounds[3].documentWidth=500,r=>r.screenshots.pop()]){const r=fixture();change(r);assert.throws(()=>verify(r,log));}});
test('zero POST reliable-save and original/higher current receipt are required',()=>{for(const change of [r=>r.cases[2].posts=1,r=>r.cases[5].actualForwardedCommit200=false,r=>r.cases[5].currentVersion=1,r=>r.cases[6].originalReadOnlyAck200=false]){const r=fixture();change(r);assert.throws(()=>verify(r,log));}});
test('actual 403409 and all three late identity protections required',()=>{for(const change of [r=>r.cases[7].actual409=200,r=>r.cases[8].actual403=200,r=>r.cases[11].originalPreserved=false,r=>r.cases[12].newActorDraftPreserved=false,r=>r.cases[13].newTokenIdentityProtected=false]){const r=fixture();change(r);assert.throws(()=>verify(r,log));}});
test('unexpected console paths statuses and incomplete owned pool shutdown fail',()=>{for(const change of [r=>r.portsFree=false,r=>r.completePoolShutdown=false,r=>r.console.push({text:'Failed to load resource:',url:'/other'}),r=>r.expectedRejections.push({path:'/api/v1/on-call/schedules/1/members',status:401})]){const r=fixture();change(r);assert.throws(()=>verify(r,log));}assert.throws(()=>verify(fixture(),'HikariPool-1 - Start completed.'));});
test('new UI preserves original frozen storage fences and independent permissions',()=>{const panel=fs.readFileSync(path.join(root,'web/src/components/OnCallPlanMemberPanel.vue'),'utf8');for(const text of ['saveMemberIntent(sessionStorage,draft)','submitMemberIntent(sessionStorage,draft)','if(!current(identity))return','draft.blocked=true','手动求成员原回执','v-model="intent.command.canRespond"','v-model="intent.command.canManage"'])assert.ok(panel.includes(text));assert.ok(panel.indexOf('saveMemberIntent(sessionStorage,draft)')<panel.indexOf('submitMemberIntent(sessionStorage,draft)'));assert.ok(panel.includes('identity.token===localStorage.getItem'));assert.ok(panel.includes('identity.actor===sessionActor()'));});
