ALTER TABLE agent_event_outbox MODIFY COLUMN next_attempt_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6);
ALTER TABLE agent_event_outbox MODIFY COLUMN lease_until TIMESTAMP(6);
ALTER TABLE agent_event_outbox MODIFY COLUMN delivered_at TIMESTAMP(6);
ALTER TABLE agent_event_outbox MODIFY COLUMN created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6);
