CREATE TABLE oncall_shift_swap (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    requester_id BIGINT NOT NULL,
    target_user_id BIGINT NOT NULL,
    request_key VARCHAR(36) NOT NULL,
    first_schedule_id BIGINT NOT NULL,
    first_shift_id BIGINT NOT NULL,
    first_version INT NOT NULL,
    first_starts_at TIMESTAMP NOT NULL,
    first_ends_at TIMESTAMP NOT NULL,
    second_schedule_id BIGINT NOT NULL,
    second_shift_id BIGINT NOT NULL,
    second_version INT NOT NULL,
    second_starts_at TIMESTAMP NOT NULL,
    second_ends_at TIMESTAMP NOT NULL,
    reason VARCHAR(500) NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    version INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    decided_at TIMESTAMP NULL,
    decided_by BIGINT NULL,
    decision_reason VARCHAR(500) NULL,
    first_replacement_shift_id BIGINT NULL,
    second_replacement_shift_id BIGINT NULL,
    CONSTRAINT fk_swap_requester FOREIGN KEY (requester_id) REFERENCES sys_user(id),
    CONSTRAINT fk_swap_target FOREIGN KEY (target_user_id) REFERENCES sys_user(id),
    CONSTRAINT fk_swap_first_schedule FOREIGN KEY (first_schedule_id) REFERENCES oncall_schedule(id),
    CONSTRAINT fk_swap_second_schedule FOREIGN KEY (second_schedule_id) REFERENCES oncall_schedule(id),
    CONSTRAINT fk_swap_first_shift FOREIGN KEY (first_shift_id) REFERENCES oncall_shift(id),
    CONSTRAINT fk_swap_second_shift FOREIGN KEY (second_shift_id) REFERENCES oncall_shift(id),
    CONSTRAINT fk_swap_decider FOREIGN KEY (decided_by) REFERENCES sys_user(id),
    CONSTRAINT fk_swap_first_replacement FOREIGN KEY (first_replacement_shift_id) REFERENCES oncall_shift(id),
    CONSTRAINT fk_swap_second_replacement FOREIGN KEY (second_replacement_shift_id) REFERENCES oncall_shift(id),
    CONSTRAINT uq_swap_request UNIQUE (requester_id, request_key),
    CONSTRAINT uq_swap_first_replacement UNIQUE (first_replacement_shift_id),
    CONSTRAINT uq_swap_second_replacement UNIQUE (second_replacement_shift_id),
    CONSTRAINT ck_swap_participants CHECK (requester_id <> target_user_id),
    CONSTRAINT ck_swap_sources CHECK (first_shift_id <> second_shift_id),
    CONSTRAINT ck_swap_status CHECK (status IN ('PENDING', 'ACCEPTED', 'REJECTED', 'WITHDRAWN'))
);
CREATE INDEX idx_swap_requester ON oncall_shift_swap(requester_id, status, id);
CREATE INDEX idx_swap_target ON oncall_shift_swap(target_user_id, status, id);
