CREATE TABLE oncall_swap_notification (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    swap_id BIGINT NOT NULL,
    event_version INT NOT NULL,
    event_status VARCHAR(16) NOT NULL,
    recipient_id BIGINT NOT NULL,
    recipient_name VARCHAR(64) NOT NULL,
    delivery_key VARCHAR(36) NOT NULL,
    payload_json TEXT NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    version INT NOT NULL DEFAULT 0,
    attempts INT NOT NULL DEFAULT 0,
    total_attempts INT NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    lease_token VARCHAR(36),
    lease_until TIMESTAMP(6),
    last_http_status INT,
    last_error_code VARCHAR(64),
    delivered_at TIMESTAMP(6),
    last_retry_from_version INT,
    last_retry_reason VARCHAR(500),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    CONSTRAINT uq_swap_notification_event UNIQUE (swap_id, event_version, recipient_id),
    CONSTRAINT uq_swap_notification_key UNIQUE (delivery_key),
    CONSTRAINT fk_swap_notification_swap FOREIGN KEY (swap_id) REFERENCES oncall_shift_swap(id),
    CONSTRAINT fk_swap_notification_recipient FOREIGN KEY (recipient_id) REFERENCES sys_user(id),
    CONSTRAINT ck_swap_notification_status CHECK (status IN ('PENDING','CLAIMED','DELIVERED','FAILED','SKIPPED')),
    CONSTRAINT ck_swap_notification_event CHECK (event_status IN ('PENDING','ACCEPTED','REJECTED','WITHDRAWN'))
);
CREATE INDEX idx_swap_notification_due ON oncall_swap_notification(status, next_attempt_at, lease_until);
